---

  language: ruby
  rvm:
    - 1.9.3
    - 2.0.0
    - 2.1.0

  before_install: rm Gemfile.lock Puppetfile.lock || true
  install:
    - sudo apt-get update
    - sudo apt-get install -y puppet facter
    - puppet --version
    - facter --version
    - bundle install
    - bundle exec librarian-puppet install

  script:
    - puppet --version
    - facter --version
    - bundle exec rake test