---

  language: ruby
  rvm:
    - 1.9.3
    - 2.0.0
    - 2.1.0

  env:
    - PUPPET_VERSION="3.6.2"
    - PUPPET_VERSION="3.7.4"

  before_install:
    # Clean up production lock files
    - rm Gemfile.lock Puppetfile.lock
    # Ensure we are getting Puppet straight from source
    - wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
    - sudo dpkg -i puppetlabs-release-precise.deb
    - sudo apt-get update
    - sudo apt-get install -qy puppet=${PUPPET_VERSION}-1puppetlabs1 facter
    # Remove warning for template_dir deprecation
    - sudo sed -ie '/template.*/d' /etc/puppet/puppet.conf
  install:
    - puppet --version
    - facter --version
    - bundle install --without puppet
    - bundle exec librarian-puppet install

  script:
    - bundle exec rake test