---
  language: ruby
  before_install: rm Gemfile.lock Puppetfile.lock || true
  install:
    - sudo apt-get update
    - sudo apt-get install -y puppet
  rvm:
    - 1.9.3
    - 2.0.0
    - 2.1.0

  script:
    - bundle exec librarian-puppet install
    - bundle exec rake test