---

classes:
  - profiles::digitalregister_app

applications:
  test-app:
    bind: '5002'
    source: 'https://github.com/mooreandrew/test-app.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.server:app'
    manage: false
    vc_server: true
    environment: 'production'
