---

classes:
  #- 'profiles::appserver'
  - 'profiles::rabbitmq'
  - 'profiles::digitalregister_app'

rabbitmq_users:
  rabbitmqadmin:
    admin: true
    password: 'rabbitmqadminrabbitmqadmin'

rabbitmq_user_permissions:
  rabbitmqadmin@/:
    configure_permission: '.*'
    read_permission: '.*'
    write_permission: '.*'

profiles::digitalregister_app::manage: false

profiles::digitalregister_app::application: 'digital-register-elasticsearch-updater'
profiles::digitalregister_app::source: 'https://github.com/LandRegistry/digital-register-elasticsearch-updater.git'
profiles::digitalregister_app::wsgi_entry: 'service.server:app'
profiles::digitalregister_app::vars:
  SQLALCHEMY_DATABASE_URI: postgresql+pg8000://postgres:password@192.16.42.61:5432/register_data
  INDEX_CONFIG_FILE_PATH: index_updaters.json
  LOGGING_CONFIG_FILE_PATH: logging_config.json
  ELASTICSEARCH_URI: http://192.16.42.55:9200
  PAGE_SIZE: '100'
  POLLING_INTERVAL_SECS: '5'
  FAULT_LOG_FILE_PATH: '/var/log/applications/digital-register-elasticsearch-updater-fault.log'
