---

classes:
  - profiles::postgresql

postgres_databases:
  register_data:
    user: register_data
    password: md5085815e3463853f3a1e9731b61ddb3a7
    owner: register_data
  user_data:
    user: user_data
    password: md5f5e1477d2e90a5760642db71ea5307d1
    owner: user_data
  transaction_data:
    user: transaction_data
    password: md5ba7c47e511be7788d5c8c11851f206a4
    owner: transaction_data
  public_account_services_data:
    user: public_account_services_data
    password: md509d623b16fdf1b322864e45c2f6dcf16
    owner: public_account_services_data

postgres_users:
  deployment:
    password_hash: md5dddbab2fa26c65fadeaa8b1076329a14
  read_only_user:
    password_hash: md59232c1755a638c620ee5985db99d8395

# Grant SELECT to all tables in transaction_data for read_only_user
# pg_db_grant:
#    test_connect_transaction_data:
#      privilege: CONNECT
#      db: transaction_data
#      role: read_only_user
#
# pg_grant:
#   read_only_user_usage_transaction_data:
#     db: transaction_data
#     role: read_only_user
#     privilege: USAGE
#     object_type: SCHEMA
#     object_name: public
#
# pg_grant:
#   read_only_user_select_transaction_data:
#     db: transaction_data
#     role: read_only_user
#     privilege: SELECT
#     object_type: ALL TABLES IN SCHEMA
#     object_name: public
