---

classes:
  - profiles::digitalregister_app

applications:
  charges-catalogue-api:
    bind: '5000'
    source: 'https://github.com/LandRegistry/charges-catalogue.git'
    app_type: 'wsgi'
    wsgi_entry: 'app:create_manager().app'
    manage: true
    revision: 'managepy'
