---

classes:
  - profiles::postgresql
  - profiles::digitalregister_app

postgres_databases:
  dm-deeds:
    user:dm-deeds 
    owner: dm-deeds 
    password: md50b6171dccaa63335d4e4f00090c32245 

applications:
dm-deed-api:
    bind: '5003'
    source: 'https://github.com/LandRegistry/dm-deed-api.git'
    app_type: 'wsgi'
    wsgi_entry: 'application:app'
    manage: true
    revision: 'develop'
    vars:
      DEED_DATABASE_URI: 'postgresql://dm-deeds:dm-deeds@localhost:5432/dm-deeds'
    require: 'Class[Postgresql::Server]'
  dm-borrower-frontend:
    bind: '5006'
    source: 'https://github.com/LandRegistry/dm-borrower-frontend.git'
    app_type: 'wsgi'
    wsgi_entry: 'application:app'
    manage: false
    revision: 'develop'
    vars:
      DEED_API_ADDRESS: 'http://localhost:5003'

profiles::postgresql::version: '9.4'
