---

classes:
  - profiles::digital_java_apps
  - profiles::postgresql
  - profiles::digitalregister_app
  - profiles::elasticsearch
  - profiles::rabbitmq

postgres_databases:
  landcharges:
    user: landcharges
    owner: landcharges
    password: md5f58cfeea810fac0c1e64c0207c3c7e18
    before: Class[Profiles::Digitalregister_app]
  db2:
    user: db2
    owner: db2
    password: md5472bc50e33575435560de57f8a9880e5
    before: Class[Profiles::Digitalregister_app]
  working:
    user: working
    owner: working
    password: md5f711274c8d7dbc6348b37c7c1c5074ce
    before: Class[Profiles::Digitalregister_app]
  docstore:
    user: docstore
    owner: docstore
    password: md549bdc15caef74ffcafd9397625f71bec
    before: Class[Profiles::Digitalregister_app]


rabbitmq_users:
  mquser:
    admin: true
    password: 'mqpassword'

rabbitmq_user_permissions:
  mquser@/:
    configure_permission: '.*'
    read_permission: '.*'
    write_permission: '.*'


applications:
  app-list:
    bind: '5000'
    source: 'https://github.com/LandRegistry-Ops/app-list.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.server:app'
    manage: false
    revision: 'master'
    vars:
      SETTINGS: 'config.DevelopmentConfig'
      APPTITLE: ''
      SERVICE: 'Land Charges'
      ENVIRONMENT: 'Integration'
      DISPLAY_LOGS: 'True'
      BASIC_AUTH_FORCE: 'False'
      BASIC_AUTH_USERNAME: 'username'
      BASIC_AUTH_PASSWORD: 'password'
      HOMEADDR: 'localhost'
  public-api:
    bind: '5001'
    source: 'https://github.com/LandRegistry/lc-public-api.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      B2B_PROCESSOR_URL: 'http://localhost:5002'
  automatic-process:
    bind: '5002'
    source: 'https://github.com/LandRegistry/lc-automatic-process.git'
    app_type: 'wsgi'
    wsgi_entry: 'application:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      RULES_ENGINE_URL: 'http://localhost:5005'
      BANKRUPTCY_DATABASE_API: 'http://localhost:5004'
      CASEWORK_DATABASE_API: 'http://localhost:5006'
  demo-utilities:
    bind: '5003'
    source: 'https://github.com/LandRegistry/lc-alpha-demo-utilities.git'
    app_type: 'wsgi'
    wsgi_entry: 'application:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      B2B_REGISTER_URL: 'http://localhost:5001'
      B2B_SEARCH_REG_URL: 'http://localhost:5004'
      B2B_SEARCH_WORK_URL: 'http://localhost:5006'
      DB2_MIGRATOR_URL: 'http://localhost:5009'
      DB2_LEGACY_URL: 'http://localhost:5007'
    require: 'Class[Postgresql::Server]'      
  land-charges:
    bind: '5004'
    source: 'https://github.com/LandRegistry/lc-land-charges.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: true
    revision: 'develop'
    vars:
      DATABASE_NAME: 'landcharges'
      DATABASE_USER: 'landcharges'
      DATABASE_PASSWORD: 'landcharges'
      DATABASE_HOST: 'localhost'
      SETTINGS: 'config.PreviewConfig'
    require: 'Class[Postgresql::Server]'
  casework-api:
    bind: '5006'
    source: 'https://github.com/LandRegistry/lc-casework-api.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: true
    revision: 'develop'
    vars:
      DATABASE_NAME: 'working'
      DATABASE_USER: 'working'
      DATABASE_PASSWORD: 'working'
      DATABASE_HOST: 'localhost'
      SETTINGS: 'config.PreviewConfig'
    require: 'Class[Postgresql::Server]'
  legacy-adapter:
    bind: '5007'
    source: 'https://github.com/LandRegistry/lc-legacy-adapter.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: true
    revision: 'develop'
    vars:
      DATABASE_NAME: 'db2'
      DATABASE_USER: 'db2'
      DATABASE_PASSWORD: 'db2'
      DATABASE_HOST: 'localhost'
      SETTINGS: 'config.PreviewConfig'
    require: 'Class[Postgresql::Server]'
  synchroniser:
    bind: '5008'
    source: 'https://github.com/LandRegistry/lc-synchroniser.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      REGISTER_URI: 'http://localhost:5004'
      LEGACY_DB_URI: 'http://localhost:5007'
    require: 'Class[Postgresql::Server]'
  migrator:
    bind: '5009'
    source: 'https://github.com/LandRegistry/lc-migrator.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      B2B_LEGACY_URL: 'http://localhost:5007'
      BANKRUPTCY_DATABASE_API: 'http://localhost:5004'
    require: 'Class[Postgresql::Server]'
  casework-frontend:
    bind: '5010'
    source: 'https://github.com/LandRegistry/lc-casework-frontend.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      CASEWORK_DB_URL: 'http://localhost:5006'
      BANKRUPTCY_DATABASE_URL: 'http://localhost:5004'
      DOCUMENT_URL: 'http://localhost:5014'
      LEGACY_URL: 'http://localhost:5007'
  error-reporting:
    bind: '5011'
    source: 'https://github.com/LandRegistry/lc-error-reporting.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      LEGACY_DB_URI: 'http://localhost:5007'
    require: 'Class[Postgresql::Server]'
  name-indexing:
    bind: '5012'
    source: 'https://github.com/LandRegistry/lc-name-indexing.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      SEARCH_API_URI: 'http://localhost:5013'
  name-search:
    bind: '5013'
    source: 'https://github.com/LandRegistry/lc-name-search.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      SEARCH_TYPE: 'phonetic'
      ELASTICSEARCH_URL: 'http://localhost:9200'
    require: Class[Profiles::Elasticsearch]
  document-api:
    bind: '5014'
    source: 'https://github.com/LandRegistry/lc-document-api.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: true
    revision: 'develop'
    vars:
      DATABASE_NAME: 'docstore'
      DATABASE_USER: 'docstore'
      DATABASE_PASSWORD: 'docstore'
      DATABASE_HOST: 'localhost'
      SETTINGS: 'config.PreviewConfig'
    require: 'Class[Postgresql::Server]'
  bankruptcy-process:
    bind: '5015'
    source: 'https://github.com/LandRegistry/lc-bankruptcy-process.git'
    app_type: 'wsgi'
    wsgi_entry: 'application.routes:app'
    manage: false
    revision: 'develop'
    vars:
      SETTINGS: 'config.PreviewConfig'
      REGISTER_URI: 'http://localhost:5004'
      LEGACY_DB_URI: 'http://localhost:5007'
      NAMES_SEARCH_URI: 'http://localhost:5013'
    require: 'Class[Postgresql::Server]'

elasticsearch_plugins:
  elasticsearch/elasticsearch-analysis-phonetic/2.7.0:
    module_dir: 'analysis-phonetic'
    instances: "es-00"

profiles::postgresql::version: '9.4'
