---

# This role is to set up a stand-alone environment for the Migration process

  classes:
    - profiles::mongodb
    - profiles::nginx
    - profiles::postgresql
    - profiles::rabbitmq
    - profiles::appserver

supervisord::config_dirs:
  - /etc/supervisord.d/*.ini
  - /etc/supervisor.d/*.conf