---

classes:
  - 'profiles::puppet::master'

# Puppet master profile managees itself
profiles::puppet::do_not_manage: true
profiles::puppet::master::deployment_key: ''
profiles::puppet::master::control_repo: 'https://github.com/LandRegistry-Ops/puppet-control.git'

profiles::puppet::puppetdb_firewall::firewall_enabled: true
profiles::puppet::puppetdb_firewall::services:
  puppet:
    range: 0.0.0.0/0
    port:  8140
  puppetdb:
    range: 0.0.0.0/0
    port: 8080  
